FROM tensorflow/tensorflow:1.14.0-gpu-py3
ADD . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python", "/app/train.py","--brightness","0.2","--rotation","180"]
CMD ["--crop_height","500","--crop_width","500"]
